# Do:
# conda env create -f environment.yml --name diarize
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - pytorch==1.11.0
  - torchvision==0.12.0
  - torchaudio==0.11.0
  - pip>=20.2
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - jupyter
  - ipykernel
  - libsndfile
  - sox
  - pip:
    - pympi-ling
    - pyannote.audio==2.1.1
    - speechbrain
    - git+https://github.com/rsprouse/audiolabel
    - git+https://github.com/rsprouse/phonlab
